// <auto-generated />
using System;
using BitLottery.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitLottery.Database.Migrations
{
    [DbContext(typeof(BitLotteryContext))]
    [Migration("20180908124632_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:shared.CustomerNumbers", "'CustomerNumbers', 'shared', '1000', '2', '', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:shared.DrawNumbers", "'DrawNumbers', 'shared', '1000', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitLottery.Models.Ballot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerId");

                    b.Property<int?>("DrawId");

                    b.Property<bool>("IsWinner");

                    b.Property<int>("Number");

                    b.Property<DateTime?>("SellDate");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DrawId");

                    b.ToTable("Ballots");
                });

            modelBuilder.Entity("BitLottery.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEXT VALUE FOR shared.CustomerNumbers");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BitLottery.Models.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DrawDate");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEXT VALUE FOR shared.DrawNumbers");

                    b.Property<DateTime>("SellUntilDate");

                    b.HasKey("Id");

                    b.ToTable("Draws");
                });

            modelBuilder.Entity("BitLottery.Models.Ballot", b =>
                {
                    b.HasOne("BitLottery.Models.Customer")
                        .WithMany("Ballots")
                        .HasForeignKey("CustomerId");

                    b.HasOne("BitLottery.Models.Draw")
                        .WithMany("Ballots")
                        .HasForeignKey("DrawId");
                });
#pragma warning restore 612, 618
        }
    }
}
